### ISSUE TITLE
Linking directly to the thread view from a comment notification is confusing

### ISSUE THREAD

**Issue by mattsacks** [usecanvas/email-templates#3]
As a member of an organization, when I get an email about a new comment with no context of the document, it's hard for me to understand what's happening on the page:

![screen shot 2016-06-15 at 9 56 46 am](https://cloud.githubusercontent.com/assets/194567/16089351/7c13495a-32df-11e6-9f12-adf9b4f76d5c.png)

/cc @max @teich

**Comment by max** [comment]
Wrong repo, can you re-open on web?
